/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectSlotTokenRouteImport } from './routes/select-slot.$token'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppPanelistsRouteImport } from './routes/_app/panelists'
import { Route as AppInterviewsRouteImport } from './routes/_app/interviews'
import { Route as AppInterviewLogsRouteImport } from './routes/_app/interview-logs'
import { Route as AppInterventionsRouteImport } from './routes/_app/interventions'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCandidatesRouteImport } from './routes/_app/candidates'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSlotTokenRoute = SelectSlotTokenRouteImport.update({
  id: '/select-slot/$token',
  path: '/select-slot/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppPanelistsRoute = AppPanelistsRouteImport.update({
  id: '/panelists',
  path: '/panelists',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewLogsRoute = AppInterviewLogsRouteImport.update({
  id: '/interview-logs',
  path: '/interview-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppInterventionsRoute = AppInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/interventions': typeof AppInterventionsRoute
  '/interview-logs': typeof AppInterviewLogsRoute
  '/interviews': typeof AppInterviewsRoute
  '/panelists': typeof AppPanelistsRoute
  '/schedule': typeof AppScheduleRoute
  '/select-slot/$token': typeof SelectSlotTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/interventions': typeof AppInterventionsRoute
  '/interview-logs': typeof AppInterviewLogsRoute
  '/interviews': typeof AppInterviewsRoute
  '/panelists': typeof AppPanelistsRoute
  '/schedule': typeof AppScheduleRoute
  '/select-slot/$token': typeof SelectSlotTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/interventions': typeof AppInterventionsRoute
  '/_app/interview-logs': typeof AppInterviewLogsRoute
  '/_app/interviews': typeof AppInterviewsRoute
  '/_app/panelists': typeof AppPanelistsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/select-slot/$token': typeof SelectSlotTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/login'
    | '/admin'
    | '/candidates'
    | '/dashboard'
    | '/feedback'
    | '/interventions'
    | '/interview-logs'
    | '/interviews'
    | '/panelists'
    | '/schedule'
    | '/select-slot/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/login'
    | '/admin'
    | '/candidates'
    | '/dashboard'
    | '/feedback'
    | '/interventions'
    | '/interview-logs'
    | '/interviews'
    | '/panelists'
    | '/schedule'
    | '/select-slot/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access-denied'
    | '/login'
    | '/_app/admin'
    | '/_app/candidates'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/interventions'
    | '/_app/interview-logs'
    | '/_app/interviews'
    | '/_app/panelists'
    | '/_app/schedule'
    | '/select-slot/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  LoginRoute: typeof LoginRoute
  SelectSlotTokenRoute: typeof SelectSlotTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-slot/$token': {
      id: '/select-slot/$token'
      path: '/select-slot/$token'
      fullPath: '/select-slot/$token'
      preLoaderRoute: typeof SelectSlotTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panelists': {
      id: '/_app/panelists'
      path: '/panelists'
      fullPath: '/panelists'
      preLoaderRoute: typeof AppPanelistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-logs': {
      id: '/_app/interview-logs'
      path: '/interview-logs'
      fullPath: '/interview-logs'
      preLoaderRoute: typeof AppInterviewLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interventions': {
      id: '/_app/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AppInterventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppInterventionsRoute: typeof AppInterventionsRoute
  AppInterviewLogsRoute: typeof AppInterviewLogsRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppPanelistsRoute: typeof AppPanelistsRoute
  AppScheduleRoute: typeof AppScheduleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppInterventionsRoute: AppInterventionsRoute,
  AppInterviewLogsRoute: AppInterviewLogsRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppPanelistsRoute: AppPanelistsRoute,
  AppScheduleRoute: AppScheduleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  LoginRoute: LoginRoute,
  SelectSlotTokenRoute: SelectSlotTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
